language: php
php:
  - 7.1
  - 7.2

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - composer validate
  - composer install
  - vendor/bin/phpcs
  - vendor/bin/phpstan analyse --no-progress -l 5 src tests
