language: php
php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4

cache:
  directories:
    - $HOME/.composer/cache

services:
  - docker

before_script:
  - composer self-update --1
  - composer validate
  - composer install
  - composer global require maglnet/composer-require-checker && $HOME/.composer/vendor/bin/composer-require-checker
  - vendor/bin/phpcs
  - vendor/bin/phpstan analyse --no-progress -l 5 src tests

after_success:
  - docker run --rm -v $(pwd):/app nyholm/roave-bc-check roave-backwards-compatibility-check:assert-backwards-compatible --from=$(git describe --tags $(git rev-list --tags --max-count=1))
